/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: 3DHaupt (https://sketchfab.com/dennish2010)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/futuristic-building-e73f9bb9981d469c8a8ccdc1f168faad
title: Futuristic Building
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function FuturisticBuilding(props) {
  const { nodes, materials } = useGLTF('/futuristic_building.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[2.86, 4.48, 17.23]}>
          <mesh geometry={nodes.Plane022_0.geometry} material={materials['s.001']} />
        </group>
        <group position={[2.91, -0.9, 1.1]}>
          <mesh geometry={nodes.Plane013_0.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Plane013_1.geometry} material={materials['Material.004']} />
        </group>
        <group position={[12.91, 0.95, 1.76]}>
          <mesh geometry={nodes.Plane012_0.geometry} material={materials['Material.003']} />
        </group>
        <group position={[10.91, 0.95, 1.76]}>
          <mesh geometry={nodes.Plane011_0.geometry} material={materials['Material.003']} />
        </group>
        <group position={[8.91, 0.95, 1.76]}>
          <mesh geometry={nodes.Plane010_0.geometry} material={materials['Material.003']} />
        </group>
        <group position={[6.91, 0.95, 1.76]}>
          <mesh geometry={nodes.Plane009_0.geometry} material={materials['Material.003']} />
        </group>
        <group position={[2.91, -1.07, 8.33]}>
          <mesh geometry={nodes.Plane008_0.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Plane008_1.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.Plane008_2.geometry} material={materials['Material.008']} />
        </group>
        <group position={[-0.09, -1.07, 8.33]}>
          <mesh geometry={nodes.Plane007_0.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Plane007_1.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.Plane007_2.geometry} material={materials['Material.008']} />
        </group>
        <group position={[-3.09, -1.07, 8.33]}>
          <mesh geometry={nodes.Plane006_0.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Plane006_1.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.Plane006_2.geometry} material={materials['Material.008']} />
        </group>
        <group position={[-6.09, -1.07, 8.33]}>
          <mesh geometry={nodes.Plane005_0.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Plane005_1.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.Plane005_2.geometry} material={materials['Material.008']} />
        </group>
        <group position={[-6.09, -1.07, 4.83]}>
          <mesh geometry={nodes.Plane004_0.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Plane004_1.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.Plane004_2.geometry} material={materials['Material.008']} />
        </group>
        <group position={[-3.09, -1.07, 4.83]}>
          <mesh geometry={nodes.Plane003_0.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Plane003_1.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.Plane003_2.geometry} material={materials['Material.008']} />
        </group>
        <group position={[-0.09, -1.07, 4.83]}>
          <mesh geometry={nodes.Plane002_0.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Plane002_1.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.Plane002_2.geometry} material={materials['Material.008']} />
        </group>
        <group position={[2.91, -1.07, 4.83]}>
          <mesh geometry={nodes.Plane001_0.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Plane001_1.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.Plane001_2.geometry} material={materials['Material.008']} />
        </group>
        <group position={[14.95, 9.08, 2.29]}>
          <mesh geometry={nodes.Plane016_0.geometry} material={materials.material_11} />
        </group>
        <group position={[14.95, 9.08, 4.63]}>
          <mesh geometry={nodes.Plane019_0.geometry} material={materials.material_11} />
        </group>
        <group position={[14.55, 9.08, 6.07]}>
          <mesh geometry={nodes.Plane018_0.geometry} material={materials.material_11} />
        </group>
        <group position={[5.94, 4.51, 6.13]}>
          <mesh geometry={nodes.Plane017_0.geometry} material={materials.material_11} />
        </group>
        <group position={[5.54, 4.51, 11.57]}>
          <mesh geometry={nodes.Plane015_0.geometry} material={materials.material_11} />
        </group>
        <group position={[5.94, 4.51, 9.32]}>
          <mesh geometry={nodes.Plane014_0.geometry} material={materials.material_11} />
        </group>
        <group position={[2.91, 4.28, 5.54]}>
          <mesh geometry={nodes.Plane_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Plane_1.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Plane_2.geometry} material={materials['Material.004_B_1']} />
          <mesh geometry={nodes.Plane_3.geometry} material={materials['Material.008']} />
          <mesh geometry={nodes.Plane_4.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Plane_5.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Plane_6.geometry} material={materials['Material.011']} />
          <mesh geometry={nodes.Plane_7.geometry} material={materials['Material.014']} />
        </group>
        <group position={[-8.3, -0.97, 11.87]}>
          <mesh geometry={nodes.Circle003_0.geometry} material={materials['Material.013']} />
        </group>
        <group position={[2.56, 3.97, -0.67]}>
          <mesh geometry={nodes.Plane020_0.geometry} material={materials['Material.005']} />
        </group>
        <group position={[6.06, -0.26, 4.21]}>
          <mesh geometry={nodes.Cube002_0.geometry} material={materials.material} />
        </group>
        <group position={[6.05, -0.28, 4.2]}>
          <mesh geometry={nodes.Circle001_0.geometry} material={materials.material} />
        </group>
        <group position={[6.06, -0.26, 5.38]}>
          <mesh geometry={nodes.Cube003_0.geometry} material={materials.material} />
        </group>
        <group position={[6.05, -0.28, 5.37]}>
          <mesh geometry={nodes.Circle002_0.geometry} material={materials.material} />
        </group>
        <group position={[9.47, 4.7, 5.6]}>
          <mesh geometry={nodes.Cube004_0.geometry} material={materials.material} />
        </group>
        <group position={[9.45, 4.7, 5.61]}>
          <mesh geometry={nodes.Circle004_0.geometry} material={materials.material} />
        </group>
        <group position={[10.79, 4.7, 5.6]}>
          <mesh geometry={nodes.Cube005_0.geometry} material={materials.material} />
        </group>
        <group position={[10.78, 4.7, 5.61]}>
          <mesh geometry={nodes.Circle005_0.geometry} material={materials.material} />
        </group>
        <group position={[10.8, 6.51, 5.6]}>
          <mesh geometry={nodes.Cube007_0.geometry} material={materials.material} />
        </group>
        <group position={[10.79, 6.51, 5.61]}>
          <mesh geometry={nodes.Circle006_0.geometry} material={materials.material} />
        </group>
        <group position={[5.78, 8.34, 8.59]}>
          <mesh geometry={nodes.Cube008_0.geometry} material={materials.material} />
        </group>
        <group position={[5.79, 8.33, 8.61]}>
          <mesh geometry={nodes.Circle008_0.geometry} material={materials.material} />
        </group>
        <group position={[9.47, 6.51, 5.6]}>
          <mesh geometry={nodes.Cube009_0.geometry} material={materials.material} />
        </group>
        <group position={[9.45, 6.51, 5.61]}>
          <mesh geometry={nodes.Circle009_0.geometry} material={materials.material} />
        </group>
        <group position={[-3.17, 8.59, 10.89]}>
          <mesh geometry={nodes.Cube010_0.geometry} material={materials.material} />
        </group>
        <group position={[-3.13, 8.6, 10.92]}>
          <mesh geometry={nodes.Circle010_0.geometry} material={materials.material} />
        </group>
        <group position={[-0.06, 8.61, 10.9]}>
          <mesh geometry={nodes.Cube011_0.geometry} material={materials.material} />
        </group>
        <group position={[-0.1, 8.6, 10.93]}>
          <mesh geometry={nodes.Circle011_0.geometry} material={materials.material} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/futuristic_building.glb')

export default FuturisticBuilding