/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Ahmed Galeb (https://sketchfab.com/AhmedGaleb)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/low-poly-building-a7ea9379362244319e13dc8b22c460c6
title: Low Poly Building
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

 function Model(props) {
  const { nodes, materials } = useGLTF('/model.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.09, 0.99, 1.57]} scale={[0.41, 0.29, 0.47]}>
            <mesh geometry={nodes.pCube2_Foundation_0.geometry} material={materials.Foundation} />
            <mesh geometry={nodes.pCube2_Walls_0.geometry} material={materials.Walls} />
          </group>
          <group position={[0, -0.1, 0]} scale={0.39}>
            <group position={[-1.06, -2.74, 0.46]} rotation={[0, 0, -0.08]}>
              <group position={[0.32, -0.06, 0]} rotation={[0, 0, 0.02]}>
                <group position={[4.61, 11.17, -0.51]} scale={[0.59, 1.38, 1]}>
                  <mesh geometry={nodes.pCube3_Window_B_0.geometry} material={materials.Window_B} />
                </group>
                <group position={[5.41, 9.39, -0.51]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.47, 1.05, 0.56]}>
                  <mesh geometry={nodes.pCube4_Flower_Box_1_0.geometry} material={materials.Flower_Box_1} />
                </group>
                <group position={[4.88, 11.37, -0.51]} scale={[0.23, 0.1, 0.85]}>
                  <mesh geometry={nodes.pCube5_Window_B_0.geometry} material={materials.Window_B} />
                </group>
                <group position={[4.88, 11.17, -0.5]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.23, 0.1, 1.32]}>
                  <mesh geometry={nodes.pCube6_Window_B_0.geometry} material={materials.Window_B} />
                </group>
                <group position={[4.61, 11.17, -3.14]} scale={[0.59, 1.38, 1]}>
                  <mesh geometry={nodes.pCube7_Window_N_0.geometry} material={materials.Window_N} />
                </group>
                <group position={[5.41, 9.39, -3.14]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.47, 1.05, 0.56]}>
                  <mesh geometry={nodes.pCube8_Flower_Box_2_0.geometry} material={materials.Flower_Box_2} />
                </group>
                <group position={[4.88, 11.37, -3.14]} scale={[0.23, 0.1, 0.85]}>
                  <mesh geometry={nodes.pCube9_Window_N_0.geometry} material={materials.Window_N} />
                </group>
                <group position={[4.88, 11.17, -3.12]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.23, 0.1, 1.32]}>
                  <mesh geometry={nodes.pCube10_Window_N_0.geometry} material={materials.Window_N} />
                </group>
                <group position={[4.61, 11.17, -5.73]} scale={[0.59, 1.38, 1]}>
                  <mesh geometry={nodes.pCube11_Window_B_0.geometry} material={materials.Window_B} />
                </group>
                <group position={[5.41, 9.39, -5.73]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.47, 1.05, 0.56]}>
                  <mesh geometry={nodes.pCube12_Flower_Box_1_0.geometry} material={materials.Flower_Box_1} />
                </group>
                <group position={[4.88, 11.37, -5.74]} scale={[0.23, 0.1, 0.85]}>
                  <mesh geometry={nodes.pCube13_Window_B_0.geometry} material={materials.Window_B} />
                </group>
                <group position={[4.88, 11.17, -5.72]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.23, 0.1, 1.32]}>
                  <mesh geometry={nodes.pCube14_Window_B_0.geometry} material={materials.Window_B} />
                </group>
              </group>
            </group>
            <group position={[-0.73, 1.85, 0.46]} rotation={[0, 0, -0.08]}>
              <group position={[0.32, -0.06, 0]} rotation={[0, 0, 0.02]}>
                <group position={[4.61, 11.17, -0.51]} scale={[0.59, 1.38, 1]}>
                  <mesh geometry={nodes.pCube3_Window_B_0_1.geometry} material={materials.Window_B} />
                </group>
                <group position={[5.41, 9.39, -0.51]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.47, 1.05, 0.56]}>
                  <mesh geometry={nodes.pCube4_Flower_Box_1_0_1.geometry} material={materials.Flower_Box_1} />
                </group>
                <group position={[4.88, 11.37, -0.51]} scale={[0.23, 0.1, 0.85]}>
                  <mesh geometry={nodes.pCube5_Window_B_0_1.geometry} material={materials.Window_B} />
                </group>
                <group position={[4.88, 11.17, -0.5]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.23, 0.1, 1.32]}>
                  <mesh geometry={nodes.pCube6_Window_B_0_1.geometry} material={materials.Window_B} />
                </group>
                <group position={[4.61, 11.17, -3.14]} scale={[0.59, 1.38, 1]}>
                  <mesh geometry={nodes.pCube7_Window_N_0_1.geometry} material={materials.Window_N} />
                </group>
                <group position={[5.41, 9.39, -3.14]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.47, 1.05, 0.56]}>
                  <mesh geometry={nodes.pCube8_Flower_Box_2_0_1.geometry} material={materials.Flower_Box_2} />
                </group>
                <group position={[4.88, 11.37, -3.14]} scale={[0.23, 0.1, 0.85]}>
                  <mesh geometry={nodes.pCube9_Window_N_0_1.geometry} material={materials.Window_N} />
                </group>
                <group position={[4.88, 11.17, -3.12]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.23, 0.1, 1.32]}>
                  <mesh geometry={nodes.pCube10_Window_N_0_1.geometry} material={materials.Window_N} />
                </group>
                <group position={[4.61, 11.17, -5.73]} scale={[0.59, 1.38, 1]}>
                  <mesh geometry={nodes.pCube11_Window_B_0_1.geometry} material={materials.Window_B} />
                </group>
                <group position={[5.41, 9.39, -5.73]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.47, 1.05, 0.56]}>
                  <mesh geometry={nodes.pCube12_Flower_Box_1_0_1.geometry} material={materials.Flower_Box_1} />
                </group>
                <group position={[4.88, 11.37, -5.74]} scale={[0.23, 0.1, 0.85]}>
                  <mesh geometry={nodes.pCube13_Window_B_0_1.geometry} material={materials.Window_B} />
                </group>
                <group position={[4.88, 11.17, -5.72]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.23, 0.1, 1.32]}>
                  <mesh geometry={nodes.pCube14_Window_B_0_1.geometry} material={materials.Window_B} />
                </group>
              </group>
            </group>
          </group>
          <group position={[-0.09, 2.53, -1.04]} scale={[0.54, 0.75, 0.54]}>
            <mesh geometry={nodes.pCube15_Walls_0.geometry} material={materials.Walls} />
            <mesh geometry={nodes.pCube15_Foundation_0.geometry} material={materials.Foundation} />
          </group>
          <group position={[-1.1, -0.1, -0.94]} rotation={[0, -Math.PI / 2, 0]} scale={0.39}>
            <group position={[-1.1, -2.74, 0.46]} rotation={[0, 0, -0.08]}>
              <group position={[0.32, -0.06, 0]} rotation={[0, 0, 0.02]}>
                <group position={[4.61, 11.17, -0.51]} scale={[0.59, 1.38, 1]}>
                  <mesh geometry={nodes.pCube3_Window_B_0_2.geometry} material={materials.Window_B} />
                </group>
                <group position={[5.41, 9.39, -0.51]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.47, 1.05, 0.56]}>
                  <mesh geometry={nodes.pCube4_Flower_Box_1_0_2.geometry} material={materials.Flower_Box_1} />
                </group>
                <group position={[4.88, 11.37, -0.51]} scale={[0.23, 0.1, 0.85]}>
                  <mesh geometry={nodes.pCube5_Window_B_0_2.geometry} material={materials.Window_B} />
                </group>
                <group position={[4.88, 11.17, -0.5]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.23, 0.1, 1.32]}>
                  <mesh geometry={nodes.pCube6_Window_B_0_2.geometry} material={materials.Window_B} />
                </group>
                <group position={[4.61, 11.17, -3.14]} scale={[0.59, 1.38, 1]}>
                  <mesh geometry={nodes.pCube7_Window_N_0_2.geometry} material={materials.Window_N} />
                </group>
                <group position={[5.41, 9.39, -3.14]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.47, 1.05, 0.56]}>
                  <mesh geometry={nodes.pCube8_Flower_Box_2_0_2.geometry} material={materials.Flower_Box_2} />
                </group>
                <group position={[4.88, 11.37, -3.14]} scale={[0.23, 0.1, 0.85]}>
                  <mesh geometry={nodes.pCube9_Window_N_0_2.geometry} material={materials.Window_N} />
                </group>
                <group position={[4.88, 11.17, -3.12]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.23, 0.1, 1.32]}>
                  <mesh geometry={nodes.pCube10_Window_N_0_2.geometry} material={materials.Window_N} />
                </group>
                <group position={[4.61, 11.17, -5.73]} scale={[0.59, 1.38, 1]}>
                  <mesh geometry={nodes.pCube11_Window_B_0_2.geometry} material={materials.Window_B} />
                </group>
                <group position={[5.41, 9.39, -5.73]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.47, 1.05, 0.56]}>
                  <mesh geometry={nodes.pCube12_Flower_Box_1_0_2.geometry} material={materials.Flower_Box_1} />
                </group>
                <group position={[4.88, 11.37, -5.74]} scale={[0.23, 0.1, 0.85]}>
                  <mesh geometry={nodes.pCube13_Window_B_0_2.geometry} material={materials.Window_B} />
                </group>
                <group position={[4.88, 11.17, -5.72]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.23, 0.1, 1.32]}>
                  <mesh geometry={nodes.pCube14_Window_B_0_2.geometry} material={materials.Window_B} />
                </group>
              </group>
            </group>
            <group position={[-0.79, 1.85, 0.46]} rotation={[0, 0, -0.08]}>
              <group position={[0.32, -0.06, 0]} rotation={[0, 0, 0.02]}>
                <group position={[4.61, 11.17, -0.51]} scale={[0.59, 1.38, 1]}>
                  <mesh geometry={nodes.pCube3_Window_B_0_3.geometry} material={materials.Window_B} />
                </group>
                <group position={[5.41, 9.39, -0.51]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.47, 1.05, 0.56]}>
                  <mesh geometry={nodes.pCube4_Flower_Box_1_0_3.geometry} material={materials.Flower_Box_1} />
                </group>
                <group position={[4.88, 11.37, -0.51]} scale={[0.23, 0.1, 0.85]}>
                  <mesh geometry={nodes.pCube5_Window_B_0_3.geometry} material={materials.Window_B} />
                </group>
                <group position={[4.88, 11.17, -0.5]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.23, 0.1, 1.32]}>
                  <mesh geometry={nodes.pCube6_Window_B_0_3.geometry} material={materials.Window_B} />
                </group>
                <group position={[4.61, 11.17, -3.14]} scale={[0.59, 1.38, 1]}>
                  <mesh geometry={nodes.pCube7_Window_N_0_3.geometry} material={materials.Window_N} />
                </group>
                <group position={[5.41, 9.39, -3.14]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.47, 1.05, 0.56]}>
                  <mesh geometry={nodes.pCube8_Flower_Box_2_0_3.geometry} material={materials.Flower_Box_2} />
                </group>
                <group position={[4.88, 11.37, -3.14]} scale={[0.23, 0.1, 0.85]}>
                  <mesh geometry={nodes.pCube9_Window_N_0_3.geometry} material={materials.Window_N} />
                </group>
                <group position={[4.88, 11.17, -3.12]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.23, 0.1, 1.32]}>
                  <mesh geometry={nodes.pCube10_Window_N_0_3.geometry} material={materials.Window_N} />
                </group>
                <group position={[4.61, 11.17, -5.73]} scale={[0.59, 1.38, 1]}>
                  <mesh geometry={nodes.pCube11_Window_B_0_3.geometry} material={materials.Window_B} />
                </group>
                <group position={[5.41, 9.39, -5.73]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.47, 1.05, 0.56]}>
                  <mesh geometry={nodes.pCube12_Flower_Box_1_0_3.geometry} material={materials.Flower_Box_1} />
                </group>
                <group position={[4.88, 11.37, -5.74]} scale={[0.23, 0.1, 0.85]}>
                  <mesh geometry={nodes.pCube13_Window_B_0_3.geometry} material={materials.Window_B} />
                </group>
                <group position={[4.88, 11.17, -5.72]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.23, 0.1, 1.32]}>
                  <mesh geometry={nodes.pCube14_Window_B_0_3.geometry} material={materials.Window_B} />
                </group>
              </group>
            </group>
          </group>
          <group position={[1, -0.1, -1.1]} rotation={[0, Math.PI / 2, 0]} scale={0.39}>
            <group position={[-0.99, -2.74, 0.46]} rotation={[0, 0, -0.08]}>
              <group position={[0.32, -0.06, 0]} rotation={[0, 0, 0.02]}>
                <group position={[4.61, 11.17, -0.51]} scale={[0.59, 1.38, 1]}>
                  <mesh geometry={nodes.pCube3_Window_B_0_4.geometry} material={materials.Window_B} />
                </group>
                <group position={[5.41, 9.39, -0.51]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.47, 1.05, 0.56]}>
                  <mesh geometry={nodes.pCube4_Flower_Box_1_0_4.geometry} material={materials.Flower_Box_1} />
                </group>
                <group position={[4.88, 11.37, -0.51]} scale={[0.23, 0.1, 0.85]}>
                  <mesh geometry={nodes.pCube5_Window_B_0_4.geometry} material={materials.Window_B} />
                </group>
                <group position={[4.88, 11.17, -0.5]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.23, 0.1, 1.32]}>
                  <mesh geometry={nodes.pCube6_Window_B_0_4.geometry} material={materials.Window_B} />
                </group>
                <group position={[4.61, 11.17, -3.14]} scale={[0.59, 1.38, 1]}>
                  <mesh geometry={nodes.pCube7_Window_N_0_4.geometry} material={materials.Window_N} />
                </group>
                <group position={[5.41, 9.39, -3.14]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.47, 1.05, 0.56]}>
                  <mesh geometry={nodes.pCube8_Flower_Box_2_0_4.geometry} material={materials.Flower_Box_2} />
                </group>
                <group position={[4.88, 11.37, -3.14]} scale={[0.23, 0.1, 0.85]}>
                  <mesh geometry={nodes.pCube9_Window_N_0_4.geometry} material={materials.Window_N} />
                </group>
                <group position={[4.88, 11.17, -3.12]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.23, 0.1, 1.32]}>
                  <mesh geometry={nodes.pCube10_Window_N_0_4.geometry} material={materials.Window_N} />
                </group>
                <group position={[4.61, 11.17, -5.73]} scale={[0.59, 1.38, 1]}>
                  <mesh geometry={nodes.pCube11_Window_B_0_4.geometry} material={materials.Window_B} />
                </group>
                <group position={[5.41, 9.39, -5.73]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.47, 1.05, 0.56]}>
                  <mesh geometry={nodes.pCube12_Flower_Box_1_0_4.geometry} material={materials.Flower_Box_1} />
                </group>
                <group position={[4.88, 11.37, -5.74]} scale={[0.23, 0.1, 0.85]}>
                  <mesh geometry={nodes.pCube13_Window_B_0_4.geometry} material={materials.Window_B} />
                </group>
                <group position={[4.88, 11.17, -5.72]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.23, 0.1, 1.32]}>
                  <mesh geometry={nodes.pCube14_Window_B_0_4.geometry} material={materials.Window_B} />
                </group>
              </group>
            </group>
            <group position={[-0.65, 1.85, 0.46]} rotation={[0, 0, -0.08]}>
              <group position={[0.32, -0.06, 0]} rotation={[0, 0, 0.02]}>
                <group position={[4.61, 11.17, -0.51]} scale={[0.59, 1.38, 1]}>
                  <mesh geometry={nodes.pCube3_Window_B_0_5.geometry} material={materials.Window_B} />
                </group>
                <group position={[5.41, 9.39, -0.51]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.47, 1.05, 0.56]}>
                  <mesh geometry={nodes.pCube4_Flower_Box_1_0_5.geometry} material={materials.Flower_Box_1} />
                </group>
                <group position={[4.88, 11.37, -0.51]} scale={[0.23, 0.1, 0.85]}>
                  <mesh geometry={nodes.pCube5_Window_B_0_5.geometry} material={materials.Window_B} />
                </group>
                <group position={[4.88, 11.17, -0.5]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.23, 0.1, 1.32]}>
                  <mesh geometry={nodes.pCube6_Window_B_0_5.geometry} material={materials.Window_B} />
                </group>
                <group position={[4.61, 11.17, -3.14]} scale={[0.59, 1.38, 1]}>
                  <mesh geometry={nodes.pCube7_Window_N_0_5.geometry} material={materials.Window_N} />
                </group>
                <group position={[5.41, 9.39, -3.14]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.47, 1.05, 0.56]}>
                  <mesh geometry={nodes.pCube8_Flower_Box_2_0_5.geometry} material={materials.Flower_Box_2} />
                </group>
                <group position={[4.88, 11.37, -3.14]} scale={[0.23, 0.1, 0.85]}>
                  <mesh geometry={nodes.pCube9_Window_N_0_5.geometry} material={materials.Window_N} />
                </group>
                <group position={[4.88, 11.17, -3.12]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.23, 0.1, 1.32]}>
                  <mesh geometry={nodes.pCube10_Window_N_0_5.geometry} material={materials.Window_N} />
                </group>
                <group position={[4.61, 11.17, -5.73]} scale={[0.59, 1.38, 1]}>
                  <mesh geometry={nodes.pCube11_Window_B_0_5.geometry} material={materials.Window_B} />
                </group>
                <group position={[5.41, 9.39, -5.73]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.47, 1.05, 0.56]}>
                  <mesh geometry={nodes.pCube12_Flower_Box_1_0_5.geometry} material={materials.Flower_Box_1} />
                </group>
                <group position={[4.88, 11.37, -5.74]} scale={[0.23, 0.1, 0.85]}>
                  <mesh geometry={nodes.pCube13_Window_B_0_5.geometry} material={materials.Window_B} />
                </group>
                <group position={[4.88, 11.17, -5.72]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.23, 0.1, 1.32]}>
                  <mesh geometry={nodes.pCube14_Window_B_0_5.geometry} material={materials.Window_B} />
                </group>
              </group>
            </group>
          </group>
          <group scale={0.39}>
            <mesh geometry={nodes.pCube18_Window_N_0.geometry} material={materials.Window_N} />
            <mesh geometry={nodes.pCube18_Door_texture_0.geometry} material={materials.Door_texture} />
          </group>
          <group position={[2.04, 1.8, -1.04]} scale={0.99}>
            <mesh geometry={nodes.pCube19_Door_texture_0.geometry} material={materials.Door_texture} />
          </group>
          <group position={[2.01, 0.95, -1.3]} rotation={[0, 0, -Math.PI / 2]} scale={0.06}>
            <mesh geometry={nodes.pSphere1_Door_texture_0.geometry} material={materials.Door_texture} />
          </group>
          <group position={[1.96, 0.3, -1.06]} scale={[0.19, 0.06, 0.25]}>
            <mesh geometry={nodes.pCube20_Stair_0.geometry} material={materials.Stair} />
          </group>
          <group position={[1.79, 0.22, -0.61]} scale={[0.39, 0.39, 0.26]}>
            <mesh geometry={nodes.pCube21_Stair_0.geometry} material={materials.Stair} />
          </group>
          <group position={[2.79, 0.14, -0.58]} scale={[0.39, 0.39, 0.42]}>
            <mesh geometry={nodes.pCube22_Stair_0.geometry} material={materials.Stair} />
          </group>
          <group position={[1.79, 0.22, -1.57]} scale={[0.39, 0.39, 0.26]}>
            <mesh geometry={nodes.pCube23_Stair_0.geometry} material={materials.Stair} />
          </group>
          <group position={[2.79, 0.14, -1.54]} scale={[0.39, 0.39, 0.42]}>
            <mesh geometry={nodes.pCube24_Stair_0.geometry} material={materials.Stair} />
          </group>
          <group position={[0, -0.05, 0]} scale={0.39}>
            <group position={[4.61, 1.66, -0.06]} scale={[0.88, 1, 0.79]}>
              <mesh geometry={nodes.pCube27_Window_onning_0.geometry} material={materials.Window_onning} />
            </group>
            <group position={[4.34, 3.19, -0.05]} rotation={[0, 0, -0.07]} scale={[0.59, 1.38, 1]}>
              <mesh geometry={nodes.pCube25_Window_B_0.geometry} material={materials.Window_B} />
              <mesh geometry={nodes.pCube25_Window_N_0.geometry} material={materials.Window_N} />
            </group>
            <group position={[4.89, 3.92, -0.05]} scale={[1, 0.6, 1.42]}>
              <mesh geometry={nodes.pCube26_Window_onning_0.geometry} material={materials.Window_onning} />
            </group>
          </group>
          <group position={[0, -0.05, -2.07]} scale={0.39}>
            <group position={[4.61, 1.66, -0.06]} scale={[0.88, 1, 0.79]}>
              <mesh geometry={nodes.pCube27_Window_onning_0_1.geometry} material={materials.Window_onning} />
            </group>
            <group position={[4.34, 3.19, -0.05]} rotation={[0, 0, -0.07]} scale={[0.59, 1.38, 1]}>
              <mesh geometry={nodes.pCube25_Window_B_0_1.geometry} material={materials.Window_B} />
              <mesh geometry={nodes.pCube25_Window_N_0_1.geometry} material={materials.Window_N} />
            </group>
            <group position={[4.89, 3.92, -0.05]} scale={[1, 0.6, 1.42]}>
              <mesh geometry={nodes.pCube26_Window_onning_0_1.geometry} material={materials.Window_onning} />
            </group>
          </group>
          <group position={[-0.44, 0.09, 1.84]} rotation={[0, 0, -0.08]} scale={0.39}>
            <group position={[4.61, 1.66, -0.06]} scale={[0.88, 1, 0.79]}>
              <mesh geometry={nodes.pCube27_Window_onning_0_2.geometry} material={materials.Window_onning} />
            </group>
            <group position={[4.34, 3.19, -0.05]} rotation={[0, 0, -0.07]} scale={[0.59, 1.38, 1]}>
              <mesh geometry={nodes.pCube25_Window_B_0_2.geometry} material={materials.Window_B} />
              <mesh geometry={nodes.pCube25_Window_N_0_2.geometry} material={materials.Window_N} />
            </group>
            <group position={[4.89, 3.92, -0.05]} scale={[1, 0.6, 1.42]}>
              <mesh geometry={nodes.pCube26_Window_onning_0_2.geometry} material={materials.Window_onning} />
            </group>
          </group>
          <group position={[-0.09, 2.13, 1.67]} scale={[0.65, 0.02, 0.53]}>
            <mesh geometry={nodes.pCube28_Trim_0.geometry} material={materials.Trim} />
            <mesh geometry={nodes.pCube28_Roof1_0.geometry} material={materials.Roof1} />
          </group>
          <group position={[-0.09, 2.13, -1.06]} scale={[0.76, 0.02, 0.75]}>
            <mesh geometry={nodes.pCube29_Trim_0.geometry} material={materials.Trim} />
          </group>
          <group position={[-0.09, 3.91, -1.06]} scale={[0.79, 0.02, 0.8]}>
            <mesh geometry={nodes.pCube30_Trim_0.geometry} material={materials.Trim} />
          </group>
          <group position={[-0.09, 5.76, -1.06]} scale={[0.84, 0.02, 0.84]}>
            <mesh geometry={nodes.pCube31_Trim_0.geometry} material={materials.Trim} />
            <mesh geometry={nodes.pCube31_Roof1_0.geometry} material={materials.Roof1} />
          </group>
          <group position={[-0.02, 1.45, -0.24]} rotation={[0.05, 0, 0]} scale={[0.39, 0.3, 0.39]}>
            <group position={[-4.23, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube33_Trim_detail_0.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-3.22, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube34_Trim_detail_0.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-2.2, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube35_Trim_detail_0.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-1.18, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube36_Trim_detail_0.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-0.17, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube37_Trim_detail_0.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[0.85, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube38_Trim_detail_0.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[1.86, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube39_Trim_detail_0.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[2.88, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube40_Trim_detail_0.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[3.9, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube41_Trim_detail_0.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[4.91, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube42_Trim_detail_0.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-5.25, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube32_Trim_detail_0.geometry} material={materials.Trim_detail} />
            </group>
          </group>
          <group position={[-0.15, 1.45, -1.86]} rotation={[3.09, 0, 3.14]} scale={[0.39, 0.3, 0.39]}>
            <group position={[-4.23, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube33_Trim_detail_0_1.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-3.22, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube34_Trim_detail_0_1.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-2.2, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube35_Trim_detail_0_1.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-1.18, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube36_Trim_detail_0_1.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-0.17, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube37_Trim_detail_0_1.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[0.85, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube38_Trim_detail_0_1.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[1.86, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube39_Trim_detail_0_1.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[2.88, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube40_Trim_detail_0_1.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[3.9, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube41_Trim_detail_0_1.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[4.91, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube42_Trim_detail_0_1.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-5.25, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube32_Trim_detail_0_1.geometry} material={materials.Trim_detail} />
            </group>
          </group>
          <group position={[0.73, 1.45, -1.07]} rotation={[Math.PI / 2, 1.52, -Math.PI / 2]} scale={[0.39, 0.3, 0.39]}>
            <group position={[-4.23, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube33_Trim_detail_0_2.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-3.22, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube34_Trim_detail_0_2.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-2.2, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube35_Trim_detail_0_2.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-1.18, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube36_Trim_detail_0_2.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-0.17, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube37_Trim_detail_0_2.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[0.85, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube38_Trim_detail_0_2.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[1.86, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube39_Trim_detail_0_2.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[2.88, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube40_Trim_detail_0_2.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[3.9, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube41_Trim_detail_0_2.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[4.91, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube42_Trim_detail_0_2.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-5.25, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube32_Trim_detail_0_2.geometry} material={materials.Trim_detail} />
            </group>
          </group>
          <group position={[-0.81, 1.48, -0.94]} rotation={[Math.PI / 2, -1.5, Math.PI / 2]} scale={[0.39, 0.3, 0.39]}>
            <group position={[-4.23, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube33_Trim_detail_0_3.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-3.22, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube34_Trim_detail_0_3.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-2.2, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube35_Trim_detail_0_3.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-1.18, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube36_Trim_detail_0_3.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-0.17, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube37_Trim_detail_0_3.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[0.85, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube38_Trim_detail_0_3.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[1.86, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube39_Trim_detail_0_3.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[2.88, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube40_Trim_detail_0_3.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[3.9, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube41_Trim_detail_0_3.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[4.91, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube42_Trim_detail_0_3.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-5.25, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube32_Trim_detail_0_3.geometry} material={materials.Trim_detail} />
            </group>
          </group>
          <group position={[0.4, -2.15, -1.07]} rotation={[Math.PI / 2, 1.5, -Math.PI / 2]} scale={[0.39, 0.3, 0.39]}>
            <group position={[-4.23, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube33_Trim_detail_0_4.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-3.22, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube34_Trim_detail_0_4.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-2.2, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube35_Trim_detail_0_4.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-1.18, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube36_Trim_detail_0_4.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-0.17, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube37_Trim_detail_0_4.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[0.85, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube38_Trim_detail_0_4.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[1.86, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube39_Trim_detail_0_4.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[2.88, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube40_Trim_detail_0_4.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[3.9, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube41_Trim_detail_0_4.geometry} material={materials.Trim_detail} />
            </group>
          </group>
          <group position={[-0.15, -2.17, -1.61]} rotation={[3.09, 0, 3.14]} scale={[0.39, 0.3, 0.39]}>
            <group position={[-4.23, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube33_Trim_detail_0_5.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-3.22, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube34_Trim_detail_0_5.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-2.2, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube35_Trim_detail_0_5.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-1.18, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube36_Trim_detail_0_5.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-0.17, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube37_Trim_detail_0_5.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[0.85, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube38_Trim_detail_0_5.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[1.86, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube39_Trim_detail_0_5.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[2.88, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube40_Trim_detail_0_5.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[3.9, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube41_Trim_detail_0_5.geometry} material={materials.Trim_detail} />
            </group>
          </group>
          <group position={[0.03, -2.01, -0.94]} rotation={[Math.PI / 2, -1.42, Math.PI / 2]} scale={[0.39, 0.3, 0.39]}>
            <group position={[-4.23, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube33_Trim_detail_0_6.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-3.22, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube34_Trim_detail_0_6.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-2.2, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube35_Trim_detail_0_6.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-1.18, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube36_Trim_detail_0_6.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-0.17, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube37_Trim_detail_0_6.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[0.85, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube38_Trim_detail_0_6.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[1.86, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube39_Trim_detail_0_6.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[2.88, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube40_Trim_detail_0_6.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[3.9, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube41_Trim_detail_0_6.geometry} material={materials.Trim_detail} />
            </group>
          </group>
          <group position={[-0.33, -0.39, -1.74]} rotation={[3.09, 0, 3.14]} scale={[0.39, 0.3, 0.39]}>
            <group position={[-4.23, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube33_Trim_detail_0_7.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-3.22, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube34_Trim_detail_0_7.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-2.2, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube35_Trim_detail_0_7.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-1.18, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube36_Trim_detail_0_7.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-0.17, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube37_Trim_detail_0_7.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[0.85, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube38_Trim_detail_0_7.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[1.86, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube39_Trim_detail_0_7.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[2.88, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube40_Trim_detail_0_7.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[3.9, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube41_Trim_detail_0_7.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-5.25, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube32_Trim_detail_0_4.geometry} material={materials.Trim_detail} />
            </group>
          </group>
          <group position={[0.61, -0.39, -1.3]} rotation={[Math.PI / 2, 1.52, -Math.PI / 2]} scale={[0.39, 0.3, 0.39]}>
            <group position={[-4.23, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube33_Trim_detail_0_8.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-3.22, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube34_Trim_detail_0_8.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-2.2, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube35_Trim_detail_0_8.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-1.18, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube36_Trim_detail_0_8.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-0.17, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube37_Trim_detail_0_8.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[0.85, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube38_Trim_detail_0_8.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[1.86, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube39_Trim_detail_0_8.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[2.88, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube40_Trim_detail_0_8.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[3.9, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube41_Trim_detail_0_8.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-5.25, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube32_Trim_detail_0_5.geometry} material={materials.Trim_detail} />
            </group>
          </group>
          <group position={[-0.69, -0.36, -0.77]} rotation={[Math.PI / 2, -1.5, Math.PI / 2]} scale={[0.39, 0.3, 0.39]}>
            <group position={[-4.23, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube33_Trim_detail_0_9.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-3.22, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube34_Trim_detail_0_9.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-2.2, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube35_Trim_detail_0_9.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-1.18, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube36_Trim_detail_0_9.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-0.17, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube37_Trim_detail_0_9.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[0.85, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube38_Trim_detail_0_9.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[1.86, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube39_Trim_detail_0_9.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[2.88, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube40_Trim_detail_0_9.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[3.9, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube41_Trim_detail_0_9.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-5.25, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube32_Trim_detail_0_6.geometry} material={materials.Trim_detail} />
            </group>
          </group>
          <group position={[0.2, -0.39, -0.36]} rotation={[0.05, 0, 0]} scale={[0.39, 0.3, 0.39]}>
            <group position={[-4.23, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube33_Trim_detail_0_10.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-3.22, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube34_Trim_detail_0_10.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-2.2, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube35_Trim_detail_0_10.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-1.18, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube36_Trim_detail_0_10.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-0.17, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube37_Trim_detail_0_10.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[0.85, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube38_Trim_detail_0_10.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[1.86, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube39_Trim_detail_0_10.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[2.88, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube40_Trim_detail_0_10.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[3.9, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube41_Trim_detail_0_10.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-5.25, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube32_Trim_detail_0_7.geometry} material={materials.Trim_detail} />
            </group>
          </group>
          <group position={[-0.15, -2.04, 2.7]} rotation={[Math.PI / 2, 1.43, -Math.PI / 2]} scale={[0.39, 0.3, 0.39]}>
            <group position={[-0.17, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube37_Trim_detail_0_11.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[0.85, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube38_Trim_detail_0_11.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[1.86, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube39_Trim_detail_0_11.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[2.88, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube40_Trim_detail_0_11.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[3.9, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube41_Trim_detail_0_11.geometry} material={materials.Trim_detail} />
            </group>
          </group>
          <group position={[0.03, -2.01, 2.83]} rotation={[Math.PI / 2, -1.42, Math.PI / 2]} scale={[0.39, 0.3, 0.39]}>
            <group position={[-4.23, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube33_Trim_detail_0_11.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-3.22, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube34_Trim_detail_0_11.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-2.2, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube35_Trim_detail_0_11.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-1.18, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube36_Trim_detail_0_11.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-0.17, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube37_Trim_detail_0_12.geometry} material={materials.Trim_detail} />
            </group>
          </group>
          <group position={[-0.21, -1.99, 1.18]} rotation={[0.16, 0, 0]} scale={[0.39, 0.3, 0.39]}>
            <group position={[-3.22, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube34_Trim_detail_0_12.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-2.2, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube35_Trim_detail_0_12.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-1.18, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube36_Trim_detail_0_12.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-0.17, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube37_Trim_detail_0_13.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[0.85, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube38_Trim_detail_0_12.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[1.86, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube39_Trim_detail_0_12.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[2.88, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube40_Trim_detail_0_12.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[3.9, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube41_Trim_detail_0_12.geometry} material={materials.Trim_detail} />
            </group>
          </group>
          <group position={[-0.63, -2.16, -0.94]} rotation={[Math.PI / 2, -1.51, Math.PI / 2]} scale={[0.39, 0.3, 0.39]}>
            <group position={[-4.23, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube33_Trim_detail_0_12.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-3.22, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube34_Trim_detail_0_13.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-2.2, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube35_Trim_detail_0_13.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-1.18, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube36_Trim_detail_0_13.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[-0.17, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube37_Trim_detail_0_14.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[0.85, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube38_Trim_detail_0_13.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[1.86, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube39_Trim_detail_0_13.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[2.88, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube40_Trim_detail_0_13.geometry} material={materials.Trim_detail} />
            </group>
            <group position={[3.9, 14.23, 3.01]} scale={[0.19, 0.31, 0.32]}>
              <mesh geometry={nodes.pCube41_Trim_detail_0_13.geometry} material={materials.Trim_detail} />
            </group>
          </group>
          <group position={[1.3, 0.15, 1.28]} rotation={[0, 0, -1.71]} scale={[0.3, 0.3, 0.39]}>
            <mesh geometry={nodes.pPlane1_lambert1_0.geometry} material={materials.lambert1} />
          </group>
          <group position={[-1.22, 6.04, -2.44]} scale={0.27}>
            <mesh geometry={nodes.pCube43_Air_condi_0.geometry} material={materials.Air_condi} />
          </group>
          <group position={[0.98, 5.61, 0.28]} scale={0.27}>
            <mesh geometry={nodes.pCube44_Air_condi_0.geometry} material={materials.Air_condi} />
          </group>
          <group position={[-0.1, 2.02, 2.26]} rotation={[-Math.PI, -0.02, -Math.PI]} scale={0.27}>
            <mesh geometry={nodes.pCube45_Air_condi_0.geometry} material={materials.Air_condi} />
          </group>
          <group position={[0.27, 0.11, 1.8]} rotation={[Math.PI, 0, 3.06]} scale={0.39}>
            <group position={[4.61, 1.66, -0.06]} scale={[0.88, 1, 0.79]}>
              <mesh geometry={nodes.pCube27_Window_onning_0_3.geometry} material={materials.Window_onning} />
            </group>
            <group position={[4.34, 3.19, -0.05]} rotation={[0, 0, -0.07]} scale={[0.59, 1.38, 1]}>
              <mesh geometry={nodes.pCube25_Window_B_0_3.geometry} material={materials.Window_B} />
              <mesh geometry={nodes.pCube25_Window_N_0_3.geometry} material={materials.Window_N} />
            </group>
            <group position={[4.89, 3.92, -0.05]} scale={[1, 0.6, 1.42]}>
              <mesh geometry={nodes.pCube26_Window_onning_0_3.geometry} material={materials.Window_onning} />
            </group>
          </group>
          <group position={[-0.17, -0.05, -0.28]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.39}>
            <group position={[4.61, 1.66, -0.06]} scale={[0.88, 1, 0.79]}>
              <mesh geometry={nodes.pCube27_Window_onning_0_4.geometry} material={materials.Window_onning} />
            </group>
            <group position={[4.34, 3.19, -0.05]} rotation={[0, 0, -0.07]} scale={[0.59, 1.38, 1]}>
              <mesh geometry={nodes.pCube25_Window_B_0_4.geometry} material={materials.Window_B} />
              <mesh geometry={nodes.pCube25_Window_N_0_4.geometry} material={materials.Window_N} />
            </group>
            <group position={[4.89, 3.92, -0.05]} scale={[1, 0.6, 1.42]}>
              <mesh geometry={nodes.pCube26_Window_onning_0_4.geometry} material={materials.Window_onning} />
            </group>
          </group>
          <group position={[-0.17, -0.05, -1.83]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.39}>
            <group position={[4.61, 1.66, -0.06]} scale={[0.88, 1, 0.79]}>
              <mesh geometry={nodes.pCube27_Window_onning_0_5.geometry} material={materials.Window_onning} />
            </group>
            <group position={[4.34, 3.19, -0.05]} rotation={[0, 0, -0.07]} scale={[0.59, 1.38, 1]}>
              <mesh geometry={nodes.pCube25_Window_B_0_5.geometry} material={materials.Window_B} />
              <mesh geometry={nodes.pCube25_Window_N_0_5.geometry} material={materials.Window_N} />
            </group>
            <group position={[4.89, 3.92, -0.05]} scale={[1, 0.6, 1.42]}>
              <mesh geometry={nodes.pCube26_Window_onning_0_5.geometry} material={materials.Window_onning} />
            </group>
          </group>
          <group position={[0.67, -0.05, -1.11]} rotation={[0, Math.PI / 2, 0]} scale={0.39}>
            <group position={[4.61, 1.66, -0.06]} scale={[0.88, 1, 0.79]}>
              <mesh geometry={nodes.pCube27_Window_onning_0_6.geometry} material={materials.Window_onning} />
            </group>
            <group position={[4.34, 3.19, -0.05]} rotation={[0, 0, -0.07]} scale={[0.59, 1.38, 1]}>
              <mesh geometry={nodes.pCube25_Window_B_0_6.geometry} material={materials.Window_B} />
              <mesh geometry={nodes.pCube25_Window_N_0_6.geometry} material={materials.Window_N} />
            </group>
            <group position={[4.89, 3.92, -0.05]} scale={[1, 0.6, 1.42]}>
              <mesh geometry={nodes.pCube26_Window_onning_0_6.geometry} material={materials.Window_onning} />
            </group>
          </group>
          <group position={[-0.79, -0.05, -1.1]} rotation={[0, Math.PI / 2, 0]} scale={0.39}>
            <group position={[4.61, 1.66, -0.06]} scale={[0.88, 1, 0.79]}>
              <mesh geometry={nodes.pCube27_Window_onning_0_7.geometry} material={materials.Window_onning} />
            </group>
            <group position={[4.34, 3.19, -0.05]} rotation={[0, 0, -0.07]} scale={[0.59, 1.38, 1]}>
              <mesh geometry={nodes.pCube25_Window_B_0_7.geometry} material={materials.Window_B} />
              <mesh geometry={nodes.pCube25_Window_N_0_7.geometry} material={materials.Window_N} />
            </group>
            <group position={[4.89, 3.92, -0.05]} scale={[1, 0.6, 1.42]}>
              <mesh geometry={nodes.pCube26_Window_onning_0_7.geometry} material={materials.Window_onning} />
            </group>
          </group>
          <group position={[0.63, 0.13, 0.95]} rotation={[0.1, -Math.PI / 2, 0]} scale={0.39}>
            <group position={[4.61, 1.66, -0.06]} scale={[0.88, 1, 0.79]}>
              <mesh geometry={nodes.pCube27_Window_onning_0_8.geometry} material={materials.Window_onning} />
            </group>
            <group position={[4.34, 3.19, -0.05]} rotation={[0, 0, -0.07]} scale={[0.59, 1.38, 1]}>
              <mesh geometry={nodes.pCube25_Window_B_0_8.geometry} material={materials.Window_B} />
              <mesh geometry={nodes.pCube25_Window_N_0_8.geometry} material={materials.Window_N} />
            </group>
            <group position={[4.89, 3.92, -0.05]} scale={[1, 0.6, 1.42]}>
              <mesh geometry={nodes.pCube26_Window_onning_0_8.geometry} material={materials.Window_onning} />
            </group>
          </group>
          <group position={[-0.83, 0.13, 0.96]} rotation={[0.1, -Math.PI / 2, 0]} scale={0.39}>
            <group position={[4.61, 1.66, -0.06]} scale={[0.88, 1, 0.79]}>
              <mesh geometry={nodes.pCube27_Window_onning_0_9.geometry} material={materials.Window_onning} />
            </group>
            <group position={[4.34, 3.19, -0.05]} rotation={[0, 0, -0.07]} scale={[0.59, 1.38, 1]}>
              <mesh geometry={nodes.pCube25_Window_B_0_9.geometry} material={materials.Window_B} />
              <mesh geometry={nodes.pCube25_Window_N_0_9.geometry} material={materials.Window_N} />
            </group>
            <group position={[4.89, 3.92, -0.05]} scale={[1, 0.6, 1.42]}>
              <mesh geometry={nodes.pCube26_Window_onning_0_9.geometry} material={materials.Window_onning} />
            </group>
          </group>
          <group position={[-0.17, -0.1, -2.1]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.39}>
            <group position={[-1.06, -2.74, 0.46]} rotation={[0, 0, -0.08]}>
              <group position={[0.32, -0.06, 0]} rotation={[0, 0, 0.02]}>
                <group position={[4.61, 11.17, -0.51]} scale={[0.59, 1.38, 1]}>
                  <mesh geometry={nodes.pCube3_Window_B_0_6.geometry} material={materials.Window_B} />
                </group>
                <group position={[5.41, 9.39, -0.51]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.47, 1.05, 0.56]}>
                  <mesh geometry={nodes.pCube4_Flower_Box_1_0_6.geometry} material={materials.Flower_Box_1} />
                </group>
                <group position={[4.88, 11.37, -0.51]} scale={[0.23, 0.1, 0.85]}>
                  <mesh geometry={nodes.pCube5_Window_B_0_6.geometry} material={materials.Window_B} />
                </group>
                <group position={[4.88, 11.17, -0.5]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.23, 0.1, 1.32]}>
                  <mesh geometry={nodes.pCube6_Window_B_0_6.geometry} material={materials.Window_B} />
                </group>
                <group position={[4.61, 11.17, -3.14]} scale={[0.59, 1.38, 1]}>
                  <mesh geometry={nodes.pCube7_Window_N_0_6.geometry} material={materials.Window_N} />
                </group>
                <group position={[5.41, 9.39, -3.14]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.47, 1.05, 0.56]}>
                  <mesh geometry={nodes.pCube8_Flower_Box_2_0_6.geometry} material={materials.Flower_Box_2} />
                </group>
                <group position={[4.88, 11.37, -3.14]} scale={[0.23, 0.1, 0.85]}>
                  <mesh geometry={nodes.pCube9_Window_N_0_6.geometry} material={materials.Window_N} />
                </group>
                <group position={[4.88, 11.17, -3.12]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.23, 0.1, 1.32]}>
                  <mesh geometry={nodes.pCube10_Window_N_0_6.geometry} material={materials.Window_N} />
                </group>
                <group position={[4.61, 11.17, -5.73]} scale={[0.59, 1.38, 1]}>
                  <mesh geometry={nodes.pCube11_Window_B_0_6.geometry} material={materials.Window_B} />
                </group>
                <group position={[5.41, 9.39, -5.73]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.47, 1.05, 0.56]}>
                  <mesh geometry={nodes.pCube12_Flower_Box_1_0_6.geometry} material={materials.Flower_Box_1} />
                </group>
                <group position={[4.88, 11.37, -5.74]} scale={[0.23, 0.1, 0.85]}>
                  <mesh geometry={nodes.pCube13_Window_B_0_6.geometry} material={materials.Window_B} />
                </group>
                <group position={[4.88, 11.17, -5.72]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.23, 0.1, 1.32]}>
                  <mesh geometry={nodes.pCube14_Window_B_0_6.geometry} material={materials.Window_B} />
                </group>
              </group>
            </group>
            <group position={[-0.73, 1.85, 0.46]} rotation={[0, 0, -0.08]}>
              <group position={[0.32, -0.06, 0]} rotation={[0, 0, 0.02]}>
                <group position={[4.61, 11.17, -0.51]} scale={[0.59, 1.38, 1]}>
                  <mesh geometry={nodes.pCube3_Window_B_0_7.geometry} material={materials.Window_B} />
                </group>
                <group position={[5.41, 9.39, -0.51]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.47, 1.05, 0.56]}>
                  <mesh geometry={nodes.pCube4_Flower_Box_1_0_7.geometry} material={materials.Flower_Box_1} />
                </group>
                <group position={[4.88, 11.37, -0.51]} scale={[0.23, 0.1, 0.85]}>
                  <mesh geometry={nodes.pCube5_Window_B_0_7.geometry} material={materials.Window_B} />
                </group>
                <group position={[4.88, 11.17, -0.5]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.23, 0.1, 1.32]}>
                  <mesh geometry={nodes.pCube6_Window_B_0_7.geometry} material={materials.Window_B} />
                </group>
                <group position={[4.61, 11.17, -3.14]} scale={[0.59, 1.38, 1]}>
                  <mesh geometry={nodes.pCube7_Window_N_0_7.geometry} material={materials.Window_N} />
                </group>
                <group position={[5.41, 9.39, -3.14]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.47, 1.05, 0.56]}>
                  <mesh geometry={nodes.pCube8_Flower_Box_2_0_7.geometry} material={materials.Flower_Box_2} />
                </group>
                <group position={[4.88, 11.37, -3.14]} scale={[0.23, 0.1, 0.85]}>
                  <mesh geometry={nodes.pCube9_Window_N_0_7.geometry} material={materials.Window_N} />
                </group>
                <group position={[4.88, 11.17, -3.12]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.23, 0.1, 1.32]}>
                  <mesh geometry={nodes.pCube10_Window_N_0_7.geometry} material={materials.Window_N} />
                </group>
                <group position={[4.61, 11.17, -5.73]} scale={[0.59, 1.38, 1]}>
                  <mesh geometry={nodes.pCube11_Window_B_0_7.geometry} material={materials.Window_B} />
                </group>
                <group position={[5.41, 9.39, -5.73]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.47, 1.05, 0.56]}>
                  <mesh geometry={nodes.pCube12_Flower_Box_1_0_7.geometry} material={materials.Flower_Box_1} />
                </group>
                <group position={[4.88, 11.37, -5.74]} scale={[0.23, 0.1, 0.85]}>
                  <mesh geometry={nodes.pCube13_Window_B_0_7.geometry} material={materials.Window_B} />
                </group>
                <group position={[4.88, 11.17, -5.72]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.23, 0.1, 1.32]}>
                  <mesh geometry={nodes.pCube14_Window_B_0_7.geometry} material={materials.Window_B} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model.glb')

export default Model